name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup BuildX
        run: echo hellow
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run the python..
        run: python healthcheck.py ${{ inputs.url }}
