name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    uses: ./.github/workflows/my-action
    name: Pass input and secrets to my-action
    with:
      username: ${{ inputs.username }}
